### ISSUE TITLE
add web app

### ISSUE THREAD

**Issue by javaswinger** [devanssound/EchoEarnings#8]
add a web app front end

it looks like currently there are commonly used frameworks that can do this:
- https://ironmansoftware.com/powershell-universal
- [ ] https://docs.powershelluniversal.com/
- https://www.systemfrontier.com/solutions/powershell/
- [ ] https://www.systemfrontier.com/kb/user-guide/
- https://badgerati.github.io/Pode.Web/
- [ ] https://github.com/Badgerati/Pode.Web
- [ ] https://badgerati.github.io/Pode.Web/Functions/Elements/Add-PodeWebTableButton/
- [ ] https://badgerati.github.io/Pode/
- [ ] https://github.com/Badgerati/Pode

**Comment by javaswinger** [comment]
Pode.Web is a GitHub project and the others are way too complicated so this would be the place ot start

**Comment by javaswinger** [comment]
Current issue is cannot get the "Calculator.ps1" to work from within the web server function as it shows this output:
```
Name                           Value
----                           -----
InputValue                     25
InputType                      H

Get-FormInputAndCalculate: Type=H, Value=25
ERROR:
The term 'Get-CalculateWagesAndTaxes' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by devanssound** [comment]
Calculations work in web app!

**Comment by devanssound** [comment]
Install Pode.Web required a workaround. Up and running with Import-Module Pode.Web 'Enter' .\server.ps1

![image](https://github.com/devanssound/EchoEarnings/assets/10003973/f2f316b7-1d1e-4e80-89e3-8710a90482b2)
